// Paddings
const TINY_PADDING = 3
const SMALL_PADDING = 6
const STANDARD_PADDING = 12
const MEDIUM_PADDING = 18
const LARGE_PADDING = 24
const XLARGE_PADDING = 36

// Sizes
const PROFILE_PICTURE_SIZE = 50
const SMALL_PROFILE_PICTURE_SIZE = 25

export {
  TINY_PADDING,
  SMALL_PADDING,
  STANDARD_PADDING,
  MEDIUM_PADDING,
  LARGE_PADDING,
  XLARGE_PADDING,
  PROFILE_PICTURE_SIZE,
  SMALL_PROFILE_PICTURE_SIZE,
}
